# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. alid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: subscription
          # Provide the Id of the subscription which should be used.
          subscriptionId: c00d16c7-6c1f-4c03-9be1-6934a4c49682
          # Specify the Id for the Management Group, only required for Management Group Deployments.
          managementGroupId: # optional
          # Provide the target region, only required for management Group or Subscription deployments.
          region: 'japan east'
          # Provide the name of a resource group.
          resourceGroupName:
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./azuredeploy.json
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
          deploymentMode: # optional, default is Incremental
          # Specifies the name of the resource group deployment to create.
          deploymentName: # optional
          # Supply deployment parameter values.
          parameters: ./azuredeployparameters.json principalId=2177251b-9226-435f-b1ec-7cfb5641188d
